#!/usr/bin/env ruby

require "hangman"

if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  $stdout.sync = true
end

game = Hangman::Game.new # go into hangman module and then class object.new
game.play # call the function play
